# Generated by Django 3.1 on 2020-08-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog post', 'verbose_name_plural': 'BlogPosts'},
        ),
    ]
